# Generated by Django 5.0.1 on 2024-01-04 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_collection_options_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="data",
            new_name="date",
        ),
    ]
